{
    # App information
    'name': 'Shopify Odoo Connector',
    'version': '19.0.6.3',
    'category': 'eCommerce',
    'summary': 'Shopify Odoo Connector',
    'license': 'OPL-1',

    # Author
    'author': 'Emipro Technologies Pvt. Ltd.',
    'website': 'http://www.emiprotechnologies.com/',
    'maintainer': 'Emipro Technologies Pvt. Ltd.',

    # Dependencies
    'depends': ['common_connector_library'],

    # Views
    'init_xml': [],
    'data': [
        'security/group.xml',
        'security/ir.model.access.csv',
        'view/instance_view.xml',
        'view/shopify_market_ept.xml',
        'wizard/res_config_view.xml',
        'data/import_order_status.xml',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/product_data.xml',
        'data/product_tag.xml',
        'data/ir_attachment_data.xml',
        'wizard/process_import_export_view.xml',
        'view/product_template_view.xml',
        'view/product_product_view.xml',
        'view/payment_gateway_view.xml',
        'view/shopify_payment_terms_view.xml',
        'wizard/queue_process_wizard_view.xml',
        'view/order_data_queue_ept.xml',
        'view/product_data_queue_view.xml',
        'view/customer_data_queue_ept.xml',
        'view/customer_data_queue_line_ept.xml',
        'view/location_ept.xml',
        'view/sale_order_view.xml',
        'view/res_partner_view.xml',
        'view/sale_workflow_config_view.xml',
        'view/stock_picking_view.xml',
        'view/stock_move_view.xml',
        'wizard/cron_configuration_ept.xml',
        'wizard/cancel_refund_order_wizard_view.xml',
        'wizard/shopify_onboarding_confirmation_ept_view.xml',
        'wizard/basic_configuration_onboarding.xml',
        'wizard/financial_status_onboarding_view.xml',
        'wizard/shopify_auth_ept_view.xml',
        'view/account_invoice_view.xml',
        'report/sale_report_view.xml',
        'view/common_log_book_view.xml',
        'view/shopify_instances_onboarding_panel_view.xml',
        'view/dashboard_view.xml',
        'view/order_data_queue_line_ept.xml',
        'view/product_data_queue_line_view.xml',
        'view/product_image_ept.xml',
        "wizard/prepare_product_for_export.xml",
        "wizard/prepare_customer_for_export.xml",
        'view/shopify_payout_report_ept.xml',
        'wizard/instance_configuration_wizard.xml',
        'view/delivery_carrier_view.xml',
        'view/export_stock_queue_view.xml',
        'view/export_stock_queue_line_view.xml',
        'view/shopify_oauth_templates.xml',
        'view/shopify_metafield_config_ept.xml',
        'view/export_metafield_queue_view.xml',
        'view/export_metafield_queue_line_view.xml',
        'view/shopify_channel_ept.xml',
        'view/shopify_customer_segment_view.xml',
        'view/shopify_lang_mapping_ept.xml',
    ],
    'demo_xml': [],
    # cloc settings
    'cloc_exclude': [
        "shopify/**/*",
        "**/*.xml",
        "report/**/*",
        "security/**/*",
        "static/**/*",
        "view/**/*",
        "data/**/*",
        "models/**/*",
        "wizard/**/*",
        "__pycache__/**/*"
         ],

    # Odoo Store Specific
    'images': ['static/description/main_screenshot.gif',],
    "description": """
          Shopify,
          Amazon,
          Woo,
          Woocommerce,
          woo-commerce,
          Shopify Connector
          """,

    'installable': True,
    'auto_install': False,
    'application': True,
    'post_init_hook': '_shopify_ept_post_init',
    'uninstall_hook': '_shopify_ept_uninstall_hook',
    'live_test_url': 'https://www.emiprotechnologies.com/r/DOh',
    'price': 500.00,
    'currency': 'EUR',
    'assets': {
        'web.assets_backend': [
            # 'shopify_ept/static/src/js/shopify_button_collapse.js',
            'shopify_ept/static/src/css/shopify_base.css',
            'shopify_ept/static/src/js/shopify_settings_tab.js',
        ],
    },
}
